#! /bin/sh

picom &
nitrogen --restore &
~/.config/polybar/launch.sh bspwm

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5  
bspc monitor HDMI-0 -d 6 7 8 9 0
bspc config border_width         3
bspc config window_gap          8
bspc config top_padding					0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# green
bspc config active_border_color \#28522e
# blue
bspc config normal_border_color  \#1b222c
# pink
bspc config focused_border_color \#f35c73
-bspc config active_border_color \#f35c73

bspc rule -a Thunderbird desktop=0
-bspc rule -a "Spotify" desktop=0 follow=on focus=on
-bspc rule -a Gimp desktop=8 state=floating follow=on
-bspc rule -a Discord desktop=6
-bspc rule -a Firefox desktop=6
-bspc rule -a pavucontrol desktop=6
-bspc rule -a mplayer2 state=floating
-bspc rule -a Kupfer.py focus=on
-bspc rule -a Screenkey manage=off
